### PR TITLE
systemd and README improvements

### PR DESCRIPTION
**Pull request by MingcongBai**
- The systemd unit now uses variable read from `/etc/conf.d/tpacpi` for threshold control;
- Reformatted README.md;

### CODE REVIEW

**Comment by teleshoes** [comment]
im undecided on this PR, so ill explain and see if you wanna make a case for it.

1) i prefer text-only readme, aesthetically; the only reason its a markdown file at all is so i can link it to flattr, since someone asked me to post a way to donate.
HOWEVER, i know my opinion on this is different that most other people's, so i should probably use something like what you wrote.
my main reason for not doing it is strictly emotional: i personally LOATHE markdown because it USES TRAILING WHITESPACE SEMANTICALLY. invisible control characters in what purports itself to be human-readable documentation....

2) ive been thinking about removing the service file, as i dont use it or maintain it, and it has nothing to do with the tool. ive kept it for two reasons: (A) it serves as a good reference example of how to use tpacpi-bat to accomplish a popular goal, and (B) many folks on arch apparently use it happily as-is.
most distros seem to be sticking with systemd, or moving to it soon, though, and having a config file for it is probably cleaner. maybe it complicates the installation though, more moving parts for n00bs.

what i think would be BEST would be to make an examples dir, and put some stuff in it like this:
/examples/batt_balance/tpacpi-balance.pl
/examples/systemd_fixed_threshold/tpacpi-bat-fixed-threshold.service
/examples/systemd_fixed_threshold/install.sh
/examples/systemd_dynamic_threshold/tpacpi-bat-dynamic-threshold.service
/examples/systemd_dynamic_threshold/tpacpi-bat-dynamic-threshold.conf
/examples/systemd_dynamic_threshold/install.sh

3) youd get the 100th commit and id be a little jealous

**Comment by MingcongBai** [comment]
> HOWEVER, i know my opinion on this is different that most other people's, so i should probably use something like what you wrote.

That's probably why I've decided to change stuff on README.md in the first place... and when I've got the systemd unit files it became a necesity in my opinion.

> (B) many folks on arch apparently use it happily as-is.

I really isn't that good mate...

> what i think would be BEST would be to make an examples dir, and put some stuff in it like this:

Alright, I will do that in a minute.

**Comment by MingcongBai** [comment]
Okay... Done to order.

I might start on writing a manpage if you would like them...

**Comment by linrunner** [comment]
I think it's a good idea and good practise(!) to separate the threshold configuration from the service file. Imho most users expect having a separate config file. However install.pl should exercise care not to overwrite an existing config file.

**Comment by teleshoes** [comment]
thanks!

**Pull request merged**
